### ISSUE TITLE
Module seems to add an extra .css onto .css files

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/devel_subthemer#26] opened 2021-11-23 03:11 UTC
I just created a subtheme with the module and left the default "Add stylesheet paths" setting as "css/custom.css"

In my new subtheme, the file was "css/custom.css.css"

I don't remember that happening in earlier versions of the module. Maybe the unintended side effect of some other changes?

**Comment by docwilmot** [comment] 2021-11-23 03:24
Sorry, was fixed but forgot to push changes, https://github.com/backdrop-contrib/devel_subthemer/commit/c27a71ab71786562289521d9347e7205e63b7afb

Dupe of https://github.com/backdrop-contrib/devel_subthemer/issues/25

**Closed as completed by docwilmot** 2021-11-23 03:24 UTC

**Comment by stpaultim** [comment] 2021-11-23 05:00
Thanks @docwilmot!
